const data = {
    products: [
        {
            _id: '1',
            name: 'Nike Blue Slim Shirts',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 0,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Nike Red Slim Shirts',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 120,
            countInStock: 4,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Nike Coton Shirts',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 160,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.0,
            numReviews: 4,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Nike Beige Slim Pants',
            category: 'Pants',
            image: '/images/p4.jpg',
            price: 150,
            countInStock: 5,
            brand: 'Nike',
            rating: 5,
            numReviews: 11,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Nike Kakis Slim Pants',
            category: 'Pants',
            image: '/images/p5.jpg',
            price: 150,
            countInStock: 2,
            brand: 'Nike',
            rating: 5,
            numReviews: 8,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nike Grey Slim Pants',
            category: 'Pants',
            image: '/images/p6.jpg',
            price: 150,
            countInStock: 1,
            brand: 'Nike',
            rating: 5,
            numReviews: 8,
            description: 'high quality product',
        },
    ],
};
export default data;